### ISSUE TITLE
DenoisE Permission Denied in MJOLNIR

### ISSUE THREAD

**Issue by andhikaprima** [uit-metabarcoding/MJOLNIR#1]
Great work as ussual. I have tried to use MJOLNIR. But I am stuck on the mjolnir4_ODIN (ODIN will generate now a list of ESVs for every non-singleton MOTU, using DnoisE). I have install DenoisE and modified the path (mjolnir4_ODIN.R) where I installed DnoisE, but it reported back that the DenoisE wasn't found or permission denied. Please your suggestion. Thank you

**Comment by uit-metabarcoding** [comment]
Hi Andhika.
Sorry. DnoisE is still not well implemented in MJOLNIR. We are currently working on it and there will be a new release of both DnoisE and MJOLNIR coming soon. So you will have to wait a few more weeks until this option is fully working. For now, you can run ODIN just with the option generate_ESV=FALSE.
