### ISSUE TITLE
Error in checkForRemoteErrors(val): one node produced an error: error in running command

### ISSUE THREAD

**Issue by Enorya** [uit-metabarcoding/MJOLNIR#2]
Hello, 

I am trying to use Mjolnir for the analysis of gut microbiomes of antarctic fishes but I have a problem when using the first command (mjolnir2_FREYJA). I end up with this error:
```
FREYJA will do paired-end alignment, demultiplexing and length filter.
sh: 1: illuminapairedend: not found
sh: 1: obigrep: not found
sh: 1: ngsfilter: not found
sh: 1: obigrep: not found
Error in checkForRemoteErrors(val) : 
  one node produced an error: error in running command
```
I think they're might be a problem with my installation of OBItools because I couldn't installed it the way you suggested, I had to create a miniconda3 environment to install it and I am not sure that your R package is able to recognize this installation.

Thank you in advance for your help

**Comment by uit-metabarcoding** [comment]
Hi,
We have added the "obipath" attribute to most of the MJOLNIR commands (except FRIGGA, LOKI and RAGNAROC which do not use OBITools).
You can now add the full path to the bin directory where the OBITools executables are located and I hope that this will fix your problem. Example:
mjolnir2_FREYJA("", cores, Lmin=299, Lmax=320, lib, demultiplexed=T, R1_motif="_R1.", R2_motif="_R2.", obipath="/home/owen/OBI/OBI-env/bin")
